name: Main Workflow

on:
  workflow_run:
    workflows:
      - "CI"
      - "CD"
    types:
      - pull_request
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI Workflow
        if: github.event_name == 'pull_request'
        run: echo "Triggering CI Workflow"
        # Add any additional CI-related actions here

      - name: Trigger CD Workflow
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "Triggering CD Workflow"
        # Add any additional CD-related actions here
